---
driver:
  name: vagrant
  customize:
    memory: 4096

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: opensuse-42.3

suites:
  - name: default
    run_list:
      - recipe[uyuni-basic::default]
    verifier:
      inspec_tests:
        - supermarket://stdevel/uyuni-inspec
    attributes:
